export const aspects: any = {
  aer: [],
  alienis: ['vacuos', 'tenebrae'],
  aqua: [],
  arbor: ['aer', 'herba'],
  auram: ['praecantatio', 'aer'],
  bestia: ['motus', 'victus'],
  cognitio: ['ignis', 'spiritus'],
  corpus: ['mortuus', 'bestia'],
  desidia: ['vinculum', 'spiritus'],
  exanimis: ['motus', 'mortuus'],
  fabrico: ['humanus', 'instrumentum'],
  fames: ['victus', 'vacuos'],
  gelum: ['ignis', 'perditio'],
  gula: ['fames', 'vacuos'],
  herba: ['victus', 'terra'],
  humanus: ['bestia', 'cognitio'],
  ignis: [],
  infernus: ['ignis', 'praecantatio'],
  instrumentum: ['humanus', 'ordo'],
  invidia: ['sensus', 'fames'],
  ira: ['telum', 'ignis'],
  iter: ['motus', 'terra'],
  limus: ['victus', 'aqua'],
  lucrum: ['humanus', 'fames'],
  lux: ['aer', 'ignis'],
  luxuria: ['corpus', 'fames'],
  machina: ['motus', 'instrumentum'],
  messis: ['herba', 'humanus'],
  metallum: ['terra', 'vitreus'],
  meto: ['messis', 'instrumentum'],
  mortuus: ['victus', 'perditio'],
  motus: ['aer', 'ordo'],
  ordo: [],
  pannus: ['instrumentum', 'bestia'],
  perditio: [],
  perfodio: ['humanus', 'terra'],
  permutatio: ['perditio', 'ordo'],
  potentia: ['ordo', 'ignis'],
  praecantatio: ['vacuos', 'potentia'],
  sano: ['ordo', 'victus'],
  sensus: ['aer', 'spiritus'],
  spiritus: ['victus', 'mortuus'],
  superbia: ['volatus', 'vacuos'],
  telum: ['instrumentum', 'ignis'],
  tempestas: ['aer', 'aqua'],
  tenebrae: ['vacuos', 'lux'],
  terra: [],
  tutamen: ['instrumentum', 'terra'],
  vacuos: ['aer', 'perditio'],
  venenum: ['aqua', 'perditio'],
  victus: ['aqua', 'terra'],
  vinculum: ['motus', 'perditio'],
  vitium: ['praecantatio', 'perditio'],
  vitreus: ['terra', 'ordo'],
  volatus: ['aer', 'motus'],
}
